### ISSUE TITLE
Password length different meet the min requirements

### ISSUE THREAD

**Issue by shadowninja024** [adtitas/ngrok-rdp#13] opened 2022-10-22 09:57 UTC
The password does not meet the password policy requirements. Check the minimum password length, password complexity and password history requirements.

More help is available by typing NET HELPMSG 2245.

There is no such global user or group: LittleFox.

More help is available by typing NET HELPMSG 3783.

The user name could not be found.

More help is available by typing NET HELPMSG 2221.

The command completed successfully.

LittleFox: No mapping between account names and security IDs was done.
LittleFox: No mapping between account names and security IDs was done.
Successfully installed! If RDP is dead, rebuild again.
IP:
"Failed to retreive NGROK authtoken - check again your authtoken"
Username: LittleFox
Password: 6454@6454
You can login now!

Unable to login

**Comment by adtitas** [comment] 2022-10-22 10:57
The issue is fixed now.

**Closed by adtitas** 2022-10-22 10:57 UTC
